apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: adventure
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/olacokers/gitopsargo.git
    targetRevision: master
    path: argo/manifest
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: helmstuff
  syncPolicy:
    automated:
      prune: false
      selfHeal: false