apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: influxdb
  namespace: default
  spec:
    releaseName: influxdb
    chart: 
      repository: 
      name: influxdb
      version: 0.2.4